elastic_search:
  username: elastic
  password: L9HY6UrJMMJbHrnIUK8r7QLn
  cloud_id: techfood-ktc:YXAtbm9ydGhlYXN0LTEuYXdzLmZvdW5kLmlvJGY3NDFmZDk3ODlkMjRhM2ZiMDNmZTM1ZmYzM2Q2OTZmJDhhNTJhZThhZjk5MzRhYmVhMGU3NmQ1MDY4N2U2ZDA2
  